export const words = {
  BANNED_LABELS: [
    'animal migration', // too difficult to understand
    'arm', // too similar to "elbow"
    'barn', // too similar to other types of buildings
    'bat', // ambiguous (animal vs. sports equipment)
    'brain', // too difficult to draw
    'coffee cup', // too similar to mug
    'circle', // when scaled down, always detected as an octogon
    'hexagon', // too similar to octogon
    'stitches', // too similar to lightning/zigzag
    'sweather', // too similar to "jacket"
    'van', // too similar to other types of vehicles
  ],
  LABELS: {
    '0': 'aircraft carrier',
    '1': 'airplane',
    '2': 'alarm clock',
    '3': 'ambulance',
    '4': 'angel',
    '5': 'animal migration',
    '6': 'ant',
    '7': 'anvil',
    '8': 'apple',
    '9': 'arm',
    '10': 'asparagus',
    '11': 'axe',
    '12': 'backpack',
    '13': 'banana',
    '14': 'bandage',
    '15': 'barn',
    '16': 'baseball bat',
    '17': 'baseball',
    '18': 'basket',
    '19': 'basketball',
    '20': 'bat',
    '21': 'bathtub',
    '22': 'beach',
    '23': 'bear',
    '24': 'beard',
    '25': 'bed',
    '26': 'bee',
    '27': 'belt',
    '28': 'bench',
    '29': 'bicycle',
    '30': 'binoculars',
    '31': 'bird',
    '32': 'birthday cake',
    '33': 'blackberry',
    '34': 'blueberry',
    '35': 'book',
    '36': 'boomerang',
    '37': 'bottlecap',
    '38': 'bowtie',
    '39': 'bracelet',
    '40': 'brain',
    '41': 'bread',
    '42': 'bridge',
    '43': 'broccoli',
    '44': 'broom',
    '45': 'bucket',
    '46': 'bulldozer',
    '47': 'bus',
    '48': 'bush',
    '49': 'butterfly',
    '50': 'cactus',
    '51': 'cake',
    '52': 'calculator',
    '53': 'calendar',
    '54': 'camel',
    '55': 'camera',
    '56': 'camouflage',
    '57': 'campfire',
    '58': 'candle',
    '59': 'cannon',
    '60': 'canoe',
    '61': 'car',
    '62': 'carrot',
    '63': 'castle',
    '64': 'cat',
    '65': 'ceiling fan',
    '66': 'cell phone',
    '67': 'cello',
    '68': 'chair',
    '69': 'chandelier',
    '70': 'church',
    '71': 'circle',
    '72': 'clarinet',
    '73': 'clock',
    '74': 'cloud',
    '75': 'coffee cup',
    '76': 'compass',
    '77': 'computer',
    '78': 'cookie',
    '79': 'cooler',
    '80': 'couch',
    '81': 'cow',
    '82': 'crab',
    '83': 'crayon',
    '84': 'crocodile',
    '85': 'crown',
    '86': 'cruise ship',
    '87': 'cup',
    '88': 'diamond',
    '89': 'dishwasher',
    '90': 'diving board',
    '91': 'dog',
    '92': 'dolphin',
    '93': 'donut',
    '94': 'door',
    '95': 'dragon',
    '96': 'dresser',
    '97': 'drill',
    '98': 'drums',
    '99': 'duck',
    '100': 'dumbbell',
    '101': 'ear',
    '102': 'elbow',
    '103': 'elephant',
    '104': 'envelope',
    '105': 'eraser',
    '106': 'eye',
    '107': 'eyeglasses',
    '108': 'face',
    '109': 'fan',
    '110': 'feather',
    '111': 'fence',
    '112': 'finger',
    '113': 'fire hydrant',
    '114': 'fireplace',
    '115': 'firetruck',
    '116': 'fish',
    '117': 'flamingo',
    '118': 'flashlight',
    '119': 'flip flops',
    '120': 'floor lamp',
    '121': 'flower',
    '122': 'flying saucer',
    '123': 'foot',
    '124': 'fork',
    '125': 'frog',
    '126': 'frying pan',
    '127': 'garden hose',
    '128': 'garden',
    '129': 'giraffe',
    '130': 'goatee',
    '131': 'golf club',
    '132': 'grapes',
    '133': 'grass',
    '134': 'guitar',
    '135': 'hamburger',
    '136': 'hammer',
    '137': 'hand',
    '138': 'harp',
    '139': 'hat',
    '140': 'headphones',
    '141': 'hedgehog',
    '142': 'helicopter',
    '143': 'helmet',
    '144': 'hexagon',
    '145': 'hockey puck',
    '146': 'hockey stick',
    '147': 'horse',
    '148': 'hospital',
    '149': 'hot air balloon',
    '150': 'hot dog',
    '151': 'hot tub',
    '152': 'hourglass',
    '153': 'house plant',
    '154': 'house',
    '155': 'hurricane',
    '156': 'ice cream',
    '157': 'jacket',
    '158': 'jail',
    '159': 'kangaroo',
    '160': 'key',
    '161': 'keyboard',
    '162': 'knee',
    '163': 'knife',
    '164': 'ladder',
    '165': 'lantern',
    '166': 'laptop',
    '167': 'leaf',
    '168': 'leg',
    '169': 'light bulb',
    '170': 'lighter',
    '171': 'lighthouse',
    '172': 'lightning',
    '173': 'line',
    '174': 'lion',
    '175': 'lipstick',
    '176': 'lobster',
    '177': 'lollipop',
    '178': 'mailbox',
    '179': 'map',
    '180': 'marker',
    '181': 'matches',
    '182': 'megaphone',
    '183': 'mermaid',
    '184': 'microphone',
    '185': 'microwave',
    '186': 'monkey',
    '187': 'moon',
    '188': 'mosquito',
    '189': 'motorbike',
    '190': 'mountain',
    '191': 'mouse',
    '192': 'moustache',
    '193': 'mouth',
    '194': 'mug',
    '195': 'mushroom',
    '196': 'nail',
    '197': 'necklace',
    '198': 'nose',
    '199': 'ocean',
    '200': 'octagon',
    '201': 'octopus',
    '202': 'onion',
    '203': 'oven',
    '204': 'owl',
    '205': 'paint can',
    '206': 'paintbrush',
    '207': 'palm tree',
    '208': 'panda',
    '209': 'pants',
    '210': 'paper clip',
    '211': 'parachute',
    '212': 'parrot',
    '213': 'passport',
    '214': 'peanut',
    '215': 'pear',
    '216': 'peas',
    '217': 'pencil',
    '218': 'penguin',
    '219': 'piano',
    '220': 'pickup truck',
    '221': 'picture frame',
    '222': 'pig',
    '223': 'pillow',
    '224': 'pineapple',
    '225': 'pizza',
    '226': 'pliers',
    '227': 'police car',
    '228': 'pond',
    '229': 'pool',
    '230': 'popsicle',
    '231': 'postcard',
    '232': 'potato',
    '233': 'power outlet',
    '234': 'purse',
    '235': 'rabbit',
    '236': 'raccoon',
    '237': 'radio',
    '238': 'rain',
    '239': 'rainbow',
    '240': 'rake',
    '241': 'remote control',
    '242': 'rhinoceros',
    '243': 'rifle',
    '244': 'river',
    '245': 'roller coaster',
    '246': 'rollerskates',
    '247': 'sailboat',
    '248': 'sandwich',
    '249': 'saw',
    '250': 'saxophone',
  },
};

export interface TranslateWord {
  [key: string]: string;
}
export const translate_words: TranslateWord = {
  'aircraft carrier': '항공모함',
  airplane: '비행기',
  'alarm clock': '알람 시계',
  ambulance: '앰뷸런스',
  angel: '천사',
  'animal migration': '동물 이주',
  ant: '개미',
  anvil: '모루',
  apple: '사과',
  arm: '팔',
  asparagus: '아스파라거스',
  axe: '도끼',
  backpack: '배낭',
  banana: '바나나',
  bandage: '붕대',
  barn: '헛간',
  'baseball bat': '야구방망이',
  baseball: '야구',
  basket: '바구니',
  basketball: '농구',
  bat: '박쥐',
  bathtub: '욕조',
  beach: '해변',
  bear: '곰',
  beard: '수염',
  bed: '침대',
  bee: '벌',
  belt: '벨트',
  bench: '벤치',
  bicycle: '자전거',
  binoculars: '쌍안경',
  bird: '새',
  'birthday cake': '생일 케이크',
  blackberry: '블랙베리',
  blueberry: '블루베리',
  book: '책',
  boomerang: '부메랑',
  bottlecap: '병뚜껑',
  bowtie: '보우타이',
  bracelet: '팔찌',
  brain: '뇌',
  bread: '빵',
  bridge: '다리',
  broccoli: '브로콜리',
  broom: '빗자루',
  bucket: '양동이',
  bulldozer: '불도저',
  bus: '버스',
  bush: '덤불',
  butterfly: '나비',
  cactus: '선인장',
  cake: '케이크',
  calculator: '계산기',
  calendar: '달력',
  camel: '낙타',
  camera: '카메라',
  camouflage: '위장',
  campfire: '모닥불',
  candle: '양초',
  cannon: '대포',
  canoe: '카누',
  car: '자동차',
  carrot: '당근',
  castle: '성',
  cat: '고양이',
  'ceiling fan': '천장 선풍기',
  'cell phone': '휴대폰',
  cello: '첼로',
  chair: '의자',
  chandelier: '샹들리에',
  church: '교회',
  circle: '원',
  clarinet: '클라리넷',
  clock: '시계',
  cloud: '구름',
  'coffee cup': '커피잔',
  compass: '나침반',
  computer: '컴퓨터',
  cookie: '쿠키',
  cooler: '냉각기',
  couch: '소파',
  cow: '소',
  crab: '게',
  crayon: '크레용',
  crocodile: '악어',
  crown: '왕관',
  'cruise ship': '크루즈 선박',
  cup: '컵',
  diamond: '다이아몬드',
  dishwasher: '식기세척기',
  'diving board': '다이빙 보드',
  dog: '개',
  dolphin: '돌고래',
  donut: '도넛',
  door: '문',
  dragon: '용',
  dresser: '서랍장',
  drill: '드릴',
  drums: '드럼',
  duck: '오리',
  dumbbell: '덤벨',
  ear: '귀',
  elbow: '팔꿈치',
  elephant: '코끼리',
  envelope: '봉투',
  eraser: '지우개',
  eye: '눈',
  eyeglasses: '안경',
  face: '얼굴',
  fan: '선풍기',
  feather: '깃털',
  fence: '울타리',
  finger: '손가락',
  'fire hydrant': '소화전',
  fireplace: '벽난로',
  firetruck: '소방차',
  fish: '물고기',
  flamingo: '플라밍고',
  flashlight: '손전등',
  'flip flops': '플립플랍',
  'floor lamp': '플로어 램프',
  flower: '꽃',
  'flying saucer': '날아다니는 접시',
  foot: '발',
  fork: '포크',
  frog: '개구리',
  'frying pan': '프라이팬',
  'garden hose': '정원 호스',
  garden: '정원',
  giraffe: '기린',
  goatee: '염소 수염',
  'golf club': '골프 클럽',
  grapes: '포도',
  grass: '풀',
  guitar: '기타',
  hamburger: '햄버거',
  hammer: '망치',
  hand: '손',
  harp: '하프',
  hat: '모자',
  headphones: '헤드폰',
  hedgehog: '고슴도치',
  helicopter: '헬리콥터',
  helmet: '헬멧',
  hexagon: '육각형',
  'hockey puck': '하키 팽크',
  'hockey stick': '하키 스틱',
  horse: '말',
  hospital: '병원',
  'hot air balloon': '열기구',
  'hot dog': '핫도그',
  'hot tub': '온수 욕조',
  hourglass: '모래시계',
  'house plant': '실내 식물',
  house: '집',
  hurricane: '허리케인',
  'ice cream': '아이스크림',
  jacket: '재킷',
  jail: '감옥',
  kangaroo: '캥거루',
  key: '열쇠',
  keyboard: '키보드',
  knee: '무릎',
  knife: '칼',
  ladder: '사다리',
  lantern: '랜턴',
  laptop: '노트북',
  leaf: '잎',
  leg: '다리',
  'light bulb': '전구',
  lighter: '라이터',
  lighthouse: '등대',
  lightning: '번개',
  line: '선',
  lion: '사자',
  lipstick: '립스틱',
  lobster: '랍스터',
  lollipop: '롤리팝',
  mailbox: '우체통',
  map: '지도',
  marker: '마커',
  matches: '성냥',
  megaphone: '메가폰',
  mermaid: '인어',
  microphone: '마이크',
  microwave: '전자레인지',
  monkey: '원숭이',
  moon: '달',
  mosquito: '모기',
  motorbike: '오토바이',
  mountain: '산',
  mouse: '쥐',
  moustache: '콧수염',
  mouth: '입',
  mug: '머그잔',
  mushroom: '버섯',
  nail: '손톱',
  necklace: '목걸이',
  nose: '코',
  ocean: '바다',
  octagon: '팔각형',
  octopus: '문어',
  onion: '양파',
  oven: '오븐',
  owl: '부엉이',
  'paint can': '페인트통',
  paintbrush: '붓',
  'palm tree': '야자수',
  panda: '판다',
  pants: '바지',
  'paper clip': '클립',
  parachute: '낙하산',
  parrot: '앵무새',
  passport: '여권',
  peanut: '땅콩',
  pear: '배',
  peas: '콩',
  pencil: '연필',
  penguin: '펭귄',
  piano: '피아노',
  'pickup truck': '픽업 트럭',
  'picture frame': '액자',
  pig: '돼지',
  pillow: '베개',
  pineapple: '파인애플',
  pizza: '피자',
  pliers: '플라이어',
  'police car': '경찰차',
  pond: '연못',
  pool: '수영장',
  popsicle: '얼음공',
  postcard: '엽서',
  potato: '감자',
  'power outlet': '콘센트',
  purse: '지갑',
  rabbit: '토끼',
  raccoon: '너구리',
  radio: '라디오',
  rain: '비',
  rainbow: '무지개',
  rake: '갈퀴',
  'remote control': '리모컨',
  rhinoceros: '코뿔소',
  rifle: '소총',
  river: '강',
  'roller coaster': '롤러코스터',
  rollerskates: '롤러스케이트',
  sailboat: '요트',
  sandwich: '샌드위치',
  saw: '톱',
  saxophone: '색소폰',
  'school bus': '스쿨 버스',
  scissors: '가위',
  scorpion: '전갈',
  screwdriver: '나사드라이버',
  'sea turtle': '바다거북',
  'see saw': '시소',
  shark: '상어',
  sheep: '양',
  shoe: '신발',
  shorts: '반바지',
  shovel: '삽',
  sink: '싱크대',
  skateboard: '스케이트보드',
  skull: '해골',
  skyscraper: '고층 빌딩',
  'sleeping bag': '침낭',
  'smiley face': '웃는 얼굴',
  snail: '달팽이',
  snake: '뱀',
  snorkel: '스노클',
  snowflake: '눈송이',
  snowman: '눈사람',
  'soccer ball': '축구공',
  sock: '양말',
  speedboat: '스피드보트',
  spider: '거미',
  spoon: '숟가락',
  spreadsheet: '스프레드시트',
  square: '정사각형',
  squiggle: '구불구불한 선',
  squirrel: '다람쥐',
  stairs: '계단',
  star: '별',
  steak: '스테이크',
  stereo: '스테레오',
  stethoscope: '청진기',
  stitches: '봉합',
  'stop sign': '정지 신호',
  stove: '가스레인지',
  strawberry: '딸기',
  streetlight: '가로등',
  'string bean': '팥',
  submarine: '잠수함',
  suitcase: '여행가방',
  sun: '해',
  swan: '백조',
  sweater: '스웨터',
  'swing set': '그네',
  sword: '검',
  syringe: '주사기',
  't-shirt': '티셔츠',
  table: '테이블',
  teapot: '티팟',
  'teddy-bear': '테디베어',
  telephone: '전화기',
  television: '텔레비전',
  'tennis racquet': '테니스 라켓',
  tent: '텐트',
  'The Eiffel Tower': '에펠탑',
  'The Great Wall of China': '만리장성',
  'The Mona Lisa': '모나리자',
  tiger: '호랑이',
  toaster: '토스터',
  toe: '발가락',
  toilet: '화장실',
  tooth: '이',
  toothbrush: '칫솔',
  toothpaste: '치약',
  tornado: '토네이도',
  tractor: '트랙터',
  'traffic light': '신호등',
  train: '기차',
  tree: '나무',
  triangle: '삼각형',
  trombone: '트롬본',
  truck: '트럭',
  trumpet: '트럼펫',
  umbrella: '우산',
  underwear: '속옷',
  van: '승합차',
  vase: '꽃병',
  violin: '바이올린',
  'washing machine': '세탁기',
  watermelon: '수박',
  waterslide: '워터슬라이드',
  whale: '고래',
  wheel: '바퀴',
  windmill: '풍차',
  'wine bottle': '와인병',
  'wine glass': '와인잔',
  wristwatch: '손목시계',
  yoga: '요가',
  zebra: '얼룩말',
  zigzag: '지그재그',
};

function getFilteredWord() {
  return Object.values(words.LABELS).filter(label => {
    return !words.BANNED_LABELS.includes(label);
  });
}
export function getOneWord() {
  const filterword = getFilteredWord();
  const randomIndex = Math.floor(Math.random() * filterword.length);
  return filterword[randomIndex];
}
